### ISSUE TITLE
how to plot data from a seurat integrated object with Grimon?

### ISSUE THREAD

**Issue by TorteloteLab** [mkanai/grimon#1]
Thank you for this beautiful work. 
I am trying to use Grimon to plot 5 different condition that I have as an integrated  Seurat object. Basically, I have a Seurat object composed by 5 different conditions integrated. How can I plot them with Grimon? It is not clear to me how to extract the umap projections from the seurat object and format them to plot with grimon.
I thank you in advance.

**Comment by mkanai** [comment]
Hi, thanks for your inquiry. I'm not super familiar with Seurat, but it looks like you can get cell embeddings via `Embeddings` function.

Based on [this tutorial](https://satijalab.org/seurat/archive/v3.0/dim_reduction_vignette.html), you can do something like:
```
library(Seurat)
pbmc <- readRDS(file = "../data/pbmc3k_final.rds")
input <- Embeddings(pbmc, reduction = "umap")[, 1:6]
```

To get the first six components of the UMAP embeddings and use it as an input to grimon. Please also have a look at our documentation about [the input format](https://github.com/mkanai/grimon#prepare-your-input).

**Comment by TorteloteLab** [comment]
Thanks a lot.
But still for whatever reason, I am still not capable of getting the color code associated with the cells. But I guess this  is question for the Seurat team.
Appreciate your help, and thanks for this tool.
